Feature/show posts
Best-offer-finder/frontend pull request #18
Opened 2024-05-20 23:09 UTC by Nevelito

![image](https://github.com/Best-offer-finder/frontend/assets/128865635/0811234f-2edd-419c-a265-aad176aa36eb)

!!! tylko jedno ogłoszenie jest bo taki limit został ustawiony na backendzie

2024-05-22 12:19 UTC, Rivixer commented
Limit jednego ogłoszenia jest ustawiony na frontendzie [TUTAJ](https://github.com/Best-offer-finder/frontend/blob/e2c3e1c5fe72ebdcce05f8f5f9f6148dc757dac6/src/features/pages/Schema/SchemaView.tsx#L18).

Po zmianie na większy strona prezentuje się następująco:
![image](https://github.com/Best-offer-finder/frontend/assets/76163846/bd2c0e29-ad5d-4514-96d6-f5bba9b09fb0)

2024-05-22 12:20 UTC, Rivixer commented on src/features/pages/Schema/SchemaView.tsx
> +import CarAdvertisement from "./CarAdvertisement"; // Upewnij się, że ścieżka jest poprawna
Upewniłeś się?

2024-05-22 19:35 UTC, kestivvi requested changes, later dismissed
Yey, nowe ficzery 🥳 Od strony wizualnej można by poprawić, żeby w każdej karcie miejsce na obrazek było o stałej ciut większej szerokości niż najszerszy obrazek. W ten sposób będzie jednolicie i tekst po prawej stronie zawsze będzie "wyjustowany do lewej", i guess.

2024-06-03 22:27 UTC, Rivixer approved these changes

2024-06-03 22:52 UTC, merged