Bof 62 removal of filters
Best-offer-finder/frontend pull request #34
Opened 2024-06-09 16:35 UTC by kestivvi

2024-06-09 21:21 UTC, Rivixer requested changes

2024-06-09 21:21 UTC, Rivixer commented on src/features/pages/Schema/SchemaEditForm.tsx
> +                // onChange={field.handleChange}
No i jak ja mam Ci z czymś takim tego PR approvenąć?

2024-06-10 10:01 UTC, kestivvi commented on src/features/pages/Schema/SchemaEditForm.tsx
> +                // onChange={field.handleChange}
Wystarczy, że Michał aproovnie :))

2024-06-10 10:15 UTC, MicNowak approved these changes, later dismissed

2024-06-10 10:41 UTC, kestivvi commented on src/features/pages/Schema/SchemaEditForm.tsx
> +                // onChange={field.handleChange}
**FU**, jednak samo approve Michała nie styknie

2024-06-10 11:28 UTC, Vertonowsky requested changes

2024-06-10 11:28 UTC, Vertonowsky commented on src/features/pages/Schema/SchemaEditForm.tsx
> +                  ) {
można wyciągnąć do jednej funkcji

2024-06-10 11:28 UTC, Vertonowsky commented on src/features/pages/Schema/SchemaEditForm.tsx
> +                }
zbędne klamry przy ifach. Jakiej konwencji się trzymaliśmy we wcześniejszych zadaniach?

2024-06-11 08:28 UTC, kestivvi commented on src/features/pages/Schema/SchemaEditForm.tsx
> +                }
żadnej xd

2024-06-11 08:31 UTC, Vertonowsky commented on src/features/pages/Schema/SchemaEditForm.tsx
> +                }
a xd No to mogą zostać xd

2024-06-11 08:47 UTC, kestivvi commented on src/features/pages/Schema/SchemaEditForm.tsx
> +                  ) {
ok, ale nie umiem w te skomplikowane zależności typów ts XD

2024-06-11 09:14 UTC, Vertonowsky approved these changes

2024-06-11 20:24 UTC, Rivixer approved these changes

2024-06-11 22:23 UTC, merged